name: Lint and Test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint-js:
    name: JS Lints
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Lint JS
      run: npm run lint:js

  lint-php:
    name: PHP Lints
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'
        coverage: none
        tools: composer, cs2pr

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Setup Composer cache
      uses: pat-s/always-upload-cache@v3.0.11
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
          ${{ runner.os }}-

    - name: Validate composer.json
      run: composer validate --no-check-all --strict
