name: Lint and Test

on:
  push:
    branches:
    - main
  pull_request:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-js:
    name: JS Lints
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Lint JS
      run: npm run lint:js

    - name: Check types
      run: npm run lint:types

  lint-php:
    name: PHP Lints
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'
        coverage: none
        tools: composer, cs2pr

    - name: Validate composer.json
      run: composer validate --no-check-all --strict

    - name: Install PHP dependencies
      uses: ramsey/composer-install@v4
      with:
        composer-options: '--prefer-dist --no-progress --no-interaction --no-scripts'

    - name: Lint PHP
      run: composer lint
